#!/usr/bin/env bash
# vim:set expandtab:shiftwidth=4:filetype=bash:
# SPDX-License-Identifier: GPL-3.0-or-later

# 
# 
# ~chewygumxx/cloudflare-ddns.git
# ::: :/cloudflare-ddns-update
# 
# 

set -euo pipefail
: "${DEBUG:=0}"

if [[ $# -ne 1 ]]; then
    printf 'usage: %s <profile>\n' "$0" >&2
    exit 2
fi
if [[ $1 == *[^[:alnum:]_.-]* || -z $1 ]]; then
    printf '%s: Invalid profile name\n' "$1" >&2
    exit 2
fi

source "${XDG_CONFIG_HOME:-$HOME/.config}/cloudflare-ddns/$1.env"
: "${API_TOKEN_URI:?API_TOKEN_URI is not set}"
: "${ZONE_ID:?ZONE_ID is not set}"
: "${RECORD_ID:?RECORD_ID is not set}"
: "${RECORD_NAME:?RECORD_NAME is not set}"
API_TOKEN="$(pass-cli item view "$API_TOKEN_URI")"
: "${TTL:=1200}"
: "${PROXIED:=false}"

current_ip="$(curl --ipv4 --silent --show-error --fail --retry 3 --retry-delay 2 \
    "https://cloudflare.com/cdn-cgi/trace" | 
    awk -F= '/^ip=/{print $2}'
)"
if ! [[ $current_ip =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
    printf '%s\n' '[ERROR] Invalid IPv4 address returned' >&2
    exit 1
fi

dns_ip="$(curl --silent --show-error --fail --retry 3 --retry-delay 2 \
    "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/dns_records/${RECORD_ID}" \
    -H "Authorization: Bearer $API_TOKEN" |
    jq -er '
        if .success
        then .result.content
        else error( ([.errors[]?.message] | join("; ") | select(length > 0)) // "unknown error" )
        end
    '
)"

if [[ "$current_ip" == "$dns_ip" ]]; then
    (( DEBUG )) && printf "%s\n" "[DEBUG] Current IP matches DNS IP: $current_ip"
    exit 0
fi

printf "%s\n" "[INFO] Current IP does not match DNS IP"
printf "%s\n" "[INFO] Current IP: $current_ip"
printf "%s\n" "[INFO] DNS IP: $dns_ip"

jq -n \
    --arg name    "$RECORD_NAME" \
    --arg ttl     "$TTL" \
    --arg content "$current_ip" \
    --arg proxied "$PROXIED" \
    --arg comment "$(basename -- "${BASH_SOURCE[0]}")" \
    '{
        name:    $name,
        ttl:     $ttl,
        type:    "A",
        content: $content,
        proxied: $proxied,
        comment: $comment
    }' |
curl --silent --show-error --fail --retry 3 --retry-delay 2 \
    "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/dns_records/${RECORD_ID}" \
    -X PATCH \
    -H "Authorization: Bearer $API_TOKEN" \
    -H "Content-Type: application/json" \
    --data-binary @- |
jq -e '
    if .success
    then .result
    else error( ([.errors[]?.message] | join("; ") | select(length > 0)) // "unknown error" )
    end
'
