#!/usr/bin/env bash
# vim:set expandtab:shiftwidth=4:filetype=bash:
# SPDX-License-Identifier: GPL-3.0-or-later
# shellcheck source=/dev/null

# 
# 
# ~chewygumxx/cloudflare-ddns.git
# ::: :/cloudflare-ddns-update
# 
# 

set -euo pipefail
: "${DEBUG:=0}"

if [[ $# -ne 1 || -z "$1" ]]; then
    printf 'usage: %s <domain>\n' "$0" >&2
    exit 2
fi
if [[ "$1" == *[^a-zA-Z0-9_.-]* ]]; then
    printf 'Invalid domain name: %s\n' "$1" >&2
    exit 2
fi

source "${XDG_CONFIG_HOME:-$HOME/.config}/cloudflare-ddns/$1.env"
: "${API_TOKEN:?API_TOKEN is not set}"
: "${ZONE_ID:?ZONE_ID is not set}"
: "${RECORD_ID:?RECORD_ID is not set}"
: "${RECORD_NAME:?RECORD_NAME is not set}"
: "${TTL:=1200}"
: "${PROXIED:=false}"

__curl() {
    command curl \
        --silent \
        --retry 3 \
        --retry-delay 2 \
        --show-error \
        --fail-with-body \
        "$@"
}

__api_call() {
    if [[ "$1" == .* ]]; then
        local jq_filter="$1"
        shift
    fi
    __curl "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/dns_records/${RECORD_ID}" \
        -H "Authorization: Bearer $API_TOKEN" \
        -H "Content-Type: application/json" \
        "$@" |
    jq --indent 4 -er "
        if   .success
        then .result${jq_filter-}
        else error( ([.errors[]?.message] | join(\"; \") | select(length > 0)) // \"unknown error\" )
        end
    "
}


# --------------
# Validate Sync
# --------------

current_ip="$(__curl --ipv4 "https://cloudflare.com/cdn-cgi/trace" | awk -F= '/^ip=/{print $2}')"
dns_ip="$(__api_call .content)"
if [[ "$current_ip" == "$dns_ip" ]]; then
    (( DEBUG )) && printf "%s\n" "[DEBUG] Current IP matches DNS IP: $current_ip"
    exit 0
fi

printf "[INFO] %s\n" "Current IP does not match DNS IP" \
    "Current IP: $current_ip" "DNS IP: $dns_ip"


# -----------
# Update DNS
# -----------

jq -n \
    --arg     name    "$RECORD_NAME" \
    --arg     content "$current_ip" \
    --arg     comment "$(basename -- "${BASH_SOURCE[0]}")" \
    --argjson ttl     "$TTL" \
    --argjson proxied "$PROXIED" \
    '{
        type:    "A",
        name:    $name,
        content: $content,
        comment: $comment,
        ttl:     $ttl,
        proxied: $proxied
    }' | __api_call -X PATCH --data-binary @-
